import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

/**
 * Flat ESLint config.
 *
 * Type-aware linting is enabled, which is what makes the rules below able to see
 * across the process boundary rather than only within a file.
 */
export default tseslint.config(
  {
    ignores: [
      'out/**',
      // The development-mode renderer built for check:ui (#103). Generated output,
      // same as out/ — linting a bundle reports on the bundler, not on this codebase.
      'out-dev/**',
      // Generated by a local knowledge-graph tool, not part of this codebase.
      'graphify-out/**',
      '.code-review-graph/**',
      'dist/**',
      'scripts/build/**',
      'coverage/**',
      'node_modules/**',
    ],
  },

  js.configs.recommended,

  // Type-aware rules apply to the application only. The tooling files below are
  // plain JS with no tsconfig behind them; running type-aware rules there would
  // report every value as `any` — noise about the linter's own view, not defects.
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Forge's own convention: an unused value is either used or deleted, but a
      // deliberately-ignored argument may be prefixed.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Axiom A2 applies to the code as well as to agents: an implicit `any` is a
      // guess about a type.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      // A floating promise in the main process means an unobserved failure, which
      // is how a workflow silently stalls.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      // Exhaustive switches over WorkflowState are load-bearing (#27).
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  // ---- Renderer -----------------------------------------------------------
  {
    files: ['src/renderer/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser,
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // The renderer has no Node access (axiom A7); importing these would compile
      // and then fail at runtime, so it is a lint error rather than a surprise.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['electron', 'node:*', 'fs', 'path', 'child_process'],
              message:
                'The renderer has no Node or Electron access. Route privileged work through the IPC contract in src/shared/ipc.ts.',
            },
            {
              group: ['**/ui/primitives/*'],
              message:
                "Import primitives from '@renderer/ui' — the single import surface — not from the primitives directory directly.",
            },
          ],
        },
      ],
    },
  },

  // The design system is the one place allowed to reach into itself.
  {
    files: ['src/renderer/src/ui/**/*.{ts,tsx}'],
    rules: { 'no-restricted-imports': 'off' },
  },

  // ---- Main and preload ---------------------------------------------------
  {
    files: ['src/main/**/*.ts', 'src/preload/**/*.ts'],
    languageOptions: {
      globals: globals.node,
    },
  },

  // ---- Axiom A6: no provider in core --------------------------------------
  //
  // The application layer talks to `IAgentRuntime` and resolves through
  // `RuntimeRegistry`. Only `src/main/runtimes/*` may name a provider or reach for
  // a concrete adapter. This is what let the #20 spike's finding — Antigravity
  // ships no headless CLI — be a scoping decision instead of a rewrite.
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/main/runtimes/**', 'src/main/index.ts', '**/*.test.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/runtimes/mockRuntime',
                '**/runtimes/*CliRuntime',
                '**/runtimes/scenario',
                '**/runtimes/claudeTrust*',
              ],
              message:
                'Axiom A6: core must not import a concrete runtime. Depend on IAgentRuntime and resolve through RuntimeRegistry. Only src/main/runtimes/* may name a provider.',
            },
          ],
        },
      ],
      // Catches the other half of A6: a provider name written into core as a string
      // literal or identifier, which an import restriction alone would not see.
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Literal[value=/(?:^|[^a-z])(?:claude|anthropic|antigravity)(?:[^a-z]|$)/i], TemplateElement[value.raw=/(?:^|[^a-z])(?:claude|anthropic|antigravity)(?:[^a-z]|$)/i]',
          message:
            'Axiom A6: no provider name outside src/main/runtimes/*. Runtime and account identifiers are opaque strings to core.',
        },
      ],
    },
  },

  // ---- ADR-004: Domain purity ---------------------------------------------
  {
    files: ['src/shared/domain/**/*.ts'],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'electron',
                'node:*',
                'fs',
                'path',
                'child_process',
                'crypto',
                'os',
                'src/main/**',
                '@main/**',
                'src/preload/**',
                'src/renderer/**',
                '@renderer/**',
                '@shared/views',
                '@shared/views/**',
                '@shared/ipc',
                '@shared/ipc/**',
                '../views*',
                '../ipc*',
                '../app*',
              ],
              message:
                'ADR-004: src/shared/domain must remain pure and not import upward or outside domain.',
            },
          ],
        },
      ],
    },
  },

  // ---- ADR-004: Views purity ----------------------------------------------
  {
    files: ['src/shared/views/**/*.ts'],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'electron',
                'node:*',
                'fs',
                'path',
                'child_process',
                'crypto',
                'os',
                'src/main/**',
                '@main/**',
                'src/preload/**',
                'src/renderer/**',
                '@renderer/**',
                '@shared/ipc',
                '@shared/ipc/**',
                '../ipc*',
                '../app*',
              ],
              message:
                'ADR-004: src/shared/views must remain pure read models and not import main, preload, renderer, or ipc transport.',
            },
          ],
        },
      ],
    },
  },

  // ---- ADR-004: Application services isolated from IPC transport ----------
  {
    files: [
      'src/main/projects/**/*.ts',
      'src/main/accounts/**/*.ts',
      'src/main/workflows/**/*.ts',
      'src/main/changesets/**/*.ts',
      'src/main/decisions/**/*.ts',
      'src/main/questions/**/*.ts',
      'src/main/bindings/**/*.ts',
      'src/main/artifacts/**/*.ts',
      'src/main/audit/**/*.ts',
      'src/main/health/**/*.ts',
      'src/main/templates/**/*.ts',
      'src/main/context/**/*.ts',
      'src/main/evidence/**/*.ts',
    ],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '@shared/ipc',
                '@shared/ipc/**',
                '**/shared/ipc*',
                '**/ipc/router*',
                '**/ipc/handlers*',
                '@main/ipc/**',
              ],
              message:
                'ADR-004: Application services must not import IPC transport. Depend on @shared/views instead.',
            },
          ],
        },
      ],
    },
  },

  // ---- ADR-004: Infrastructure downward direction -------------------------
  {
    files: [
      'src/main/db/**/*.ts',
      'src/main/process/**/*.ts',
      'src/main/git/**/*.ts',
      'src/main/terminal/**/*.ts',
      'src/main/logging/**/*.ts',
    ],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/projects/**',
                '**/accounts/**',
                '**/workflows/**',
                '**/changesets/**',
                '**/decisions/**',
                '**/questions/**',
                '**/bindings/**',
                '**/artifacts/**',
                '**/audit/**',
                '**/health/**',
                '**/templates/**',
                '**/core/**',
                '**/runtimes/**',
                '**/providers/**',
              ],
              message:
                'ADR-004: Infrastructure must not import application services, execution, or runtime adapters.',
            },
          ],
        },
      ],
    },
  },

  // ---- ADR-004: DB schema and drizzle-orm privacy -------------------------
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/main/db/**', '**/*.test.{ts,tsx}', 'scripts/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['drizzle-orm', 'drizzle-orm/**', '**/db/schema*'],
              message:
                'ADR-004: Database table schemas and drizzle-orm queries must remain private to src/main/db/*. Application code must interact via Store/Repository abstractions.',
            },
          ],
        },
      ],
    },
  },

  // ---- ADR-004: Runtime adapters isolated from application services -------
  {
    files: ['src/main/runtimes/**/*.ts', 'src/main/providers/**/*.ts'],
    ignores: ['**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/projects/**',
                '**/accounts/**',
                '**/workflows/**',
                '**/changesets/**',
                '**/decisions/**',
                '**/questions/**',
                '**/bindings/**',
                '**/artifacts/**',
                '**/audit/**',
                '**/health/**',
                '**/templates/**',
              ],
              message:
                'ADR-004: Runtime and provider adapters must not import application service internals. Configuration and paths must cross the boundary via SessionOptions or constructor parameters.',
            },
          ],
        },
      ],
    },
  },

  // ---- Shared -------------------------------------------------------------
  {
    files: ['src/shared/**/*.ts'],
    rules: {
      // Shared code compiles into all three targets, so it must stay
      // environment-free: no Node, no Electron, no React.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['electron', 'node:*', 'react', 'react-dom'],
              message:
                'src/shared is compiled into main, preload, and renderer. Keep it to pure data and pure functions.',
            },
          ],
        },
      ],
    },
  },

  // ---- Tests and checks ---------------------------------------------------
  {
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },
  {
    // The verification scripts and standalone CLI are run outside the app,
    // and print to stdout by design.
    files: ['scripts/**/*.{cjs,mjs,js}', 'eslint.config.js', 'src/main/cli.ts', 'bin/**/*.{ts,js}'],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'off',
    },
  },
  {
    files: ['scripts/**/*.mjs', 'eslint.config.js'],
    languageOptions: { sourceType: 'module' },
  },
  {
    files: ['electron.vite.config.ts', 'vitest.config.ts'],
    extends: [tseslint.configs.strictTypeChecked],
    languageOptions: {
      globals: globals.node,
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },

  // Must stay last so formatting rules lose to Prettier.
  prettier,
)
